// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace RateMyClasses.Migrations.Moderators
{
    [DbContext(typeof(ModeratorsContext))]
    partial class ModeratorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("RateMyClasses.Models.Moderators", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("hash");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Moderators");
                });
#pragma warning restore 612, 618
        }
    }
}
